config/routes.rb
Rails.application.routes.draw do

  root 'sales#index'

  resources :sales, only: [:index, :new, :create]
  resources :sales do
    collection do
      get 'simulate'
      get 'delete_all'
    end
  end

end

app/models/sale.rb
class Sale < ActiveRecord::Base
  validates_presence_of :units, :first_name, :last_name, :address, :city,
    :country, :credit_card_number, :credit_card_date, :credit_card_ccv

  validates_numericality_of :units, :credit_card_number, :credit_card_ccv

  validate :check_cc_date

  after_create :update_sales_feed

  scope :unshipped, ->{ where shipped: false }
  scope :shipped, ->{ where shipped: true }

  geocoded_by :build_address
  after_validation :geocode

  def build_address
    [self.city, self.state, self.country].compact.join(', ')
  end

  def check_cc_date
    if self.credit_card_date == nil
      return errors.add(:base, 'Credit Card Expiration Date must be valid numbers')
    end

    month_str, year_str = self.credit_card_date.split("/")[0],
                          self.credit_card_date.split("/")[1]
    month_str = month_str[1] if month_str[0] == "0"

    begin
      month = Integer(month_str)
      year = Integer(year_str)
    rescue ArgumentError, TypeError
      return errors.add(:base, 'Credit Card Expiration Date must be valid numbers')
    end

    begin
      date = Date.new(year, month, 1).end_of_month
    rescue ArgumentError
      return errors.add(:base, 'Credit Card Expiration Date must be valid')
    end

    if date < Date.today
      return errors.add(:base, 'Credit Card Expiration Date must be current month or later')
    end
  end

  def self.create_sale
    units = rand(1..25)
    first_name = %w(Todd Dave Morgan Rachel Jordan Lakshmi Amol Eberly Dan Janny).sample
    last_name = %w(Lynam Backus Liu Wedlake Muramoto Leong Lane).sample
    address = ['123 Water Rd', '2005 43rd Ave E', '9606 Wharf St', '5216 Ravenna Ave E',
              '4221 E Blaine St', 'One Boundary Lane'].sample
    address2 = [nil, 'Unit C', 'Apt 202'].sample
    zip = [98020, 98112, 98101, 95123, 95112].sample

    #data for maps
    city_data = [
      ['Edmonds', 'USA', 'Washington'],
      ['Seattle', 'USA'],
      ['Santa Clara', 'USA', 'California'],
      ['San Francisco', 'USA'],
      ['Mexico City', 'Mexico'],
      ['Warsaw', 'Poland'],
      ['Moscow', 'Russia'],
      ['Shanghai', 'China'],
      ['Jakarta', 'Indonesia'],
      ['Paris', 'France'],
      ['London', 'England'],
      ['Honolulu', 'USA'],
      ['New York City', 'USA'],
      ['Miami', 'USA'],
      ['Berlin', 'Germany'],
      ['Tokyo', 'Japan'],
      ['San Paulo', 'Brazil'],
      ['Sydney', 'Austrailia'],
      ['Johannesburg', 'South Africa'],
      ['Tripoli', 'Libya'],
      ['Bombay', 'India'],
      ['Santiago', 'Chile']
    ].sample

    city = city_data[0]
    country = city_data[1]
    state = city_data[2]

    cc_number = rand(100000000000000..999999999999999)
    cc_expiration = "#{rand(1..12)}/#{Date.today.year + rand(1..5)}"
    cc_ccv = rand(100..999)

    sale = Sale.new(units: units, first_name: first_name, last_name: last_name,
                    address: address, address2: address2, city: city, state: state,
                    zip: zip, country: country, credit_card_number: cc_number,
                    credit_card_date: cc_expiration, credit_card_ccv: cc_ccv)
    sale.save!
  end

  def update_sales_feed
    Pusher['sales_channel'].trigger('new_sale', {
      message: {
        units_sold: Sale.all.pluck(:units).sum,
        first_name: self.first_name,
        units: self.units,
        city: self.city,
        country: self.country,
        shipped: self.shipped
      }
    })
  end

  def self.ship_sales
    unshipped.update_all(shipped: true)
    update_map
  end

  def self.update_map
    marker_data = Gmaps4rails.build_markers(Sale.all) do |sale, marker|
      marker.lat sale.latitude
      marker.lng sale.longitude
    end

    Pusher['sales_channel'].trigger('update_map', {
      message: {
        marker_data: marker_data
      }
    })
  end

  def self.update_shipping_stats
    Pusher['sales_channel'].trigger('new_shipment', {
      message: {
        units_shipped: Sale.shipped.pluck(:units).sum
      }
    })
  end

  def self.simulate_sales(sleep_period: 0)
    rand(3..10).times do
      create_sale
    end
    sleep sleep_period #Add delay to prevent map from reloading too often
    ship_sales
    update_shipping_stats
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController

  def index
    @title = 'Jolt Cola Sales'
    @sales = Sale.all
    @hash = Gmaps4rails.build_markers(@sales) do |sale, marker|
      marker.lat sale.latitude
      marker.lng sale.longitude
    end
  end

  def new
    @title = 'Purchase Your Jolt Cola'
    @sale = Sale.new
  end

  def create
    @sale = Sale.new sale_params

    if @sale.save
      redirect_to sales_path, notice: 'Thank you for purchases Jolt Cola.  Feel the excitement!'
    else
      render 'new'
    end
  end

  def simulate
    Sale.simulate_sales
    redirect_to sales_path
  end

  def delete_all
    Sale.all.delete_all
    redirect_to sales_path
  end

  private
  def sale_params
    params.require(:sale).permit :id, :units, :first_name, :last_name, :address,
      :address2, :city, :zip, :country, :credit_card_number, :credit_card_date,
      :credit_card_ccv
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @title %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <script src="http://maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
    <script src='http://google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/sales/index.html.erb
<div class="well home_header">
  <h1 id="buy_header">Buy Jolt Now!</h1>

  <%= image_tag("jolt_revolt.jpg", size: "300x400") %><br>

  <%= link_to 'Purcahse Jolt!', new_sale_path, class: "btn btn-success btn-lg", id: "purchase_button" %><br>
  <%= link_to 'Simulate Sales', simulate_sales_path, class: "btn btn-warning btn-lg", id: "purchase_button" %>
  <%= link_to 'Delete Sales', delete_all_sales_path, class: "btn btn-danger btn-lg", id: "purchase_button" %><br>

  <h3>
  <div id="units_sold">Sold: <%= Sale.all.pluck(:units).sum %></div>
  <div id="units_shipped">Shipped: <%= Sale.shipped.pluck(:units).sum %></div>
  </h3>
</div>

<div class="col-xs-12">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h1 class="panel-title">Geographical Shipments</h1>
    </div>
    <div class="panel-body">
      <div id="map" style='width: 100%; height: 600px;'></div>
    </div>
  </div>
</div>

<div class="col-xs-12">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h1 class="panel-title">Sale Details</h1>
    </div>
    <div class="panel-body">
      <div class="table-responsive">
        <table class="table" id="sale_names">
          <thead>
            <th>First Name</th>
            <th>Quantity</th>
            <th>City</th>
            <th>Country</th>
          </thead>
          <tbody>
            <% @sales.each do |sale| %>
            <tr>
              <td><%= sale.first_name %></td>
              <td><%= sale.units %></td>
              <td><%= sale.city %></td>
              <td><%= sale.country %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<script src="//js.pusher.com/2.2/pusher.min.js"></script>
<script>
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });

  // Enable pusher logging - don't include this in production
  // Pusher.log = function(message) {
  //   if (window.console && window.console.log) {
  //     window.console.log(message);
  //   }
  // };

  var pusher = new Pusher('dbeefee1fadf19b8ac8c');
  var channel = pusher.subscribe('sales_channel');

  channel.bind('new_sale', function(data) {
    $('#units_sold').text(data.message.units_sold)
    $('#units_shipped').text(data.message.units_shipped)

    $('#sale_names').find('tbody')
      .append($('<tr>')
        .append($('<td>')
          .text(data.message.first_name)
        )
        .append($('<td>')
          .text(data.message.units)
        )
        .append($('<td>')
          .text(data.message.city)
        )
        .append($('<td>')
          .text(data.message.country)
        )
      )
  });

  channel.bind('new_shipment', function(data) {
    $('#units_shipped').text(data.message.units_shipped)
  });

  channel.bind('update_map', function(data) {
    // handler = Gmaps.build('Google');
    handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
      markers = handler.addMarkers(data.message.marker_data);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
    });
  });
</script>

app/views/sales/new.html.erb
<div class="col-xs-12">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h1 class="panel-title">New Sale</h1>
    </div>
    <div class="panel-body">
      <%= form_for @sale, :html => {:class => "form-horizontal"} do |f| %>
        <% if @sale.errors.any? %>
          <div id="error_explanation" class="alert alert-danger" role="alert">
            <ul>
            <% @sale.errors.full_messages.each do |message| %>
              <h3><li><%= message %></li></h3>
            <% end %>
            </ul>
          </div>
        <% end %>
        <div class="field form-group">
          <%= f.label :units, "Cases", class: "col-xs-2 control-label" %>
          <div class="col-xs-1">
            <%= f.number_field :units, class: "form-control", :autofocus => true %>
          </div>
        </div>
        <div class="field form-group">
          <%= f.label :first_name, "First Name", class: "col-sm-2 control-label" %>
          <div class="col-sm-2 col-xs-3">
            <%= f.text_field :first_name, class: "form-control" %>
          </div>
        </div>
        <div class="field form-group">
          <%= f.label :last_name, "Last Name", class: "col-sm-2 control-label" %>
          <div class="col-sm-2 col-xs-3">
            <%= f.text_field :last_name, class: "form-control" %>
          </div>
        </div>
        <div class="field form-group">
          <%= f.label :address, class: "col-sm-2 control-label" %>
          <div class="col-sm-2 col-xs-3">
            <%= f.text_field :address, class: "form-control" %>
          </div>
        </div>
        <div class="field form-group">
          <%= f.label :address2, class: "col-sm-2 control-label" %>
          <div class="col-sm-2 col-xs-3">
            <%= f.text_field :address2, class: "form-control" %>
          </div>
        </div>
        <div class="field form-group">
          <%= f.label :city, class: "col-sm-2 control-label" %>
          <div class="col-sm-2 col-xs-3">
            <%= f.text_field :city, class: "form-control" %>
          </div>
        </div>
        <div class="field form-group">
          <%= f.label :state, "State/Providence", class: "col-sm-2 control-label" %>
          <div class="col-sm-2 col-xs-3">
            <%= f.text_field :state, class: "form-control" %>
          </div>
        </div>
        <div class="field form-group">
          <%= f.label :zip, "Zip/Postal Code", class: "col-sm-2 control-label" %>
          <div class="col-sm-2 col-xs-3">
            <%= f.text_field :zip, class: "form-control" %>
          </div>
        </div>
        <div class="field form-group">
          <%= f.label :country, class: "col-sm-2 control-label" %>
          <div class="col-sm-2 col-xs-3">
            <%= f.text_field :country, class: "form-control" %>
          </div>
        </div>
        <div class="field form-group">
          <%= f.label :credit_card_number, "Credit Card Number", class: "col-sm-2 control-label" %>
          <div class="col-sm-2 col-xs-3">
            <%= f.text_field :credit_card_number, class: "form-control" %>
          </div>
        </div>
        <div class="field form-group">
          <%= f.label :credit_card_date, "Credit Card Expiration", class: "col-sm-2 control-label" %>
          <div class="col-sm-2 col-xs-3">
            <%= f.text_field :credit_card_date, placeholder: 'MM/YYYY', class: "form-control" %>
          </div>
        </div>
        <div class="field form-group">
          <%= f.label :credit_card_ccv, "Credit Card CCV", class: "col-sm-2 control-label" %>
          <div class="col-xs-1">
            <%= f.text_field :credit_card_ccv, class: "form-control" %>
          </div>
        </div>
        <div class="actions form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <%= f.submit class: "btn btn-success" %>
          </div>
        </div>
      <% end %>

      <%= link_to "Back", :back %>
    </div>
  </div>
</div>